# This is a basic workflow to help you get started with Actions.
# It runs on pushes to the main branch and on pull requests.

name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Run on ubuntu or windows can change this as needed
    strategy:
      matrix:
        python-version: ['3.11']  # Define a matrix of Python versions

    steps:
    - uses: actions/checkout@v4
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}   # Set up the Python version you need for your project from the matrix

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      # Install the required libraries

    - name: Run Ollama Setup
      run: |
        chmod +x ./ollamaSetup/install.sh
        ./ollamaSetup/install.sh